#!/usr/bin/env perl


$polyphredscore=shift;
$polyphredquality=shift;
$phrap1=shift;
$phrap2=shift;
$phrap3=shift;
$phrap4=shift;
$phrap5=shift;
$phrap6=shift;
$phrap7=shift;
$phrap8=shift;
$phrap9=shift;
$phrap10=shift;
$phrap11=shift;
$phrap12=shift;
$phrap13=shift;
$phrap14=shift;
$phrap15=shift;
$phrap16=shift;
$phrap17=shift;
$phrap18=shift;
print "SeqQual process with diploid_ab1 routine.\n\n";
print "Alignment with Phrap and Polyphred.\n";
print "Phrap parameters:\n";
print "Default_qual=$phrap1\n";
print "Trim_start=$phrap2\n";
print "Force_level=$phrap3\n";
print "Bybass_level=$phrap4\n";
print "Maxgap=$phrap5\n";
print "Repeat_stringency=$phrap6\n";
print "Nodeseg=$phrap7\n";
print "Nodespace=$phrap8\n";
print "Qual_show=$phrap9\n";
print "Max_subclone_size=$phrap10\n";
print "Trim_score=$phrap11\n";
print "Trim_penalty=$phrap12\n";
print "Trim_qual=$phrap13\n";
print "Confirm_length=$phrap14\n";
print "Confirm_trim=$phrap15\n";
print "Confirm_penalty=$phrap16\n";
print "Confirm_score=$phrap17\n";
print "Indexwordsize=$phrap18\n";
print "Polyphred parameters:\n";
print "Polyphred_score=$polyphredscore\n";
print "Polyphred_quality=$polyphredquality\n\n";
